AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Doc Q&A Portal - RAG Backend with Pinecone and OpenRouter

# Parameters for API keys (passed at deploy time)
Parameters:
  OpenRouterApiKey:
    Type: String
    Description: OpenRouter API Key (for LLM and embeddings)
    NoEcho: true
  PineconeApiKey:
    Type: String
    Description: Pinecone API Key
    NoEcho: true
  PineconeIndex:
    Type: String
    Description: Pinecone Index Name
    Default: doc-qa-index

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        OPENROUTER_API_KEY: !Ref OpenRouterApiKey
        PINECONE_API_KEY: !Ref PineconeApiKey
        PINECONE_INDEX: !Ref PineconeIndex

Resources:
  # API Gateway
  DocQaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET, POST, DELETE, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      # Enable throttling at the API stage level (10 requests per minute)
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 0.17

  # Usage Plan for API Rate Limiting
  DocQaApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: DocQaApiprodStage
    Properties:
      UsagePlanName: doc-qa-usage-plan
      Description: Rate limiting plan for Doc Q&A API
      Throttle:
        BurstLimit: 10         # Max concurrent requests
        RateLimit: 0.17        # ~10 requests per minute (10/60)
      Quota:
        Limit: 10000       # Max requests per day
        Period: DAY
      ApiStages:
        - ApiId: !Ref DocQaApi
          Stage: prod


  # Ping Lambda Function (health check)
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-ping
      CodeUri: ./
      Handler: dist/handlers/ping.handler
      Description: Health check endpoint
      Events:
        PingApi:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /ping
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/ping.ts

  # Ingest Lambda Function (async - writes to S3, queues to SQS)
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-ingest
      CodeUri: ./
      Handler: dist/handlers/ingest.handler
      Description: Accepts documents, writes to S3, queues to SQS for async processing
      Environment:
        Variables:
          DOC_BUCKET: !Ref DocQaBucket
          INGEST_QUEUE_URL: !Ref IngestQueue
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocQaBucket
        - SQSSendMessagePolicy:
            QueueName: !GetAtt IngestQueue.QueueName
      Events:
        IngestApi:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /ingest
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/ingest.ts

  # Ask Lambda Function
  AskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-ask
      CodeUri: ./
      Handler: dist/handlers/ask.handler
      Description: Answers questions using RAG with Pinecone and OpenRouter
      Events:
        AskApi:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /ask
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/ask.ts

  # Documents Lambda Function (list, get content, delete)
  DocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-documents
      CodeUri: ./
      Handler: dist/handlers/documents.handler
      Description: Lists, gets content, and deletes documents from Pinecone
      Events:
        ListDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /documents
            Method: GET
        GetDocumentContent:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /documents/{docId}/content
            Method: GET
        DeleteDocument:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /documents/{docId}
            Method: DELETE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/documents.ts

  # ============================================
  # UPLOAD URL FUNCTION (Presigned S3 URLs)
  # ============================================

  UploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-upload-url
      CodeUri: ./
      Handler: dist/handlers/upload-url.handler
      Description: Generates presigned S3 URLs for direct file uploads
      Environment:
        Variables:
          DOC_BUCKET: !Ref DocQaBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocQaBucket
      Events:
        UploadUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref DocQaApi
            Path: /upload-url
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/upload-url.ts

  # ============================================
  # ASYNC INGEST RESOURCES (S3 + SQS + Worker)
  # ============================================

  # S3 Bucket for storing documents before processing
  DocQaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "doc-qa-ingest-${AWS::AccountId}"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt IngestQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter7Days
            Status: Enabled
            ExpirationInDays: 7

  # Dead Letter Queue for failed messages
  IngestDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: doc-qa-ingest-dlq
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS Queue for ingest jobs
  IngestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: doc-qa-ingest-queue
      VisibilityTimeout: 300  # 5 minutes (> Lambda timeout)
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IngestDeadLetterQueue.Arn
        maxReceiveCount: 3  # Retry 3 times before DLQ

  # SQS Queue Policy - Allow S3 to send messages
  IngestQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IngestQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt IngestQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::doc-qa-ingest-${AWS::AccountId}"

  # Ingest Worker Lambda (processes SQS messages)
  IngestWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-qa-ingest-worker
      CodeUri: ./
      Handler: dist/handlers/ingest-worker.handler
      Timeout: 120  # 2 minutes for processing
      MemorySize: 1024
      Description: Processes async ingest jobs from SQS
      Environment:
        Variables:
          DOC_BUCKET: !Ref DocQaBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocQaBucket
        - S3CrudPolicy:
            BucketName: !Ref DocQaBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - textract:DetectDocumentText
                - textract:AnalyzeDocument
              Resource: '*'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt IngestQueue.Arn
            BatchSize: 1  # Process one at a time
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/handlers/ingest-worker.ts

  # ============================================
  # CLOUDWATCH MONITORING
  # ============================================

  # Log Groups with Retention
  AskFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AskFunction}
      RetentionInDays: 14

  IngestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${IngestFunction}
      RetentionInDays: 14

  IngestWorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${IngestWorkerFunction}
      RetentionInDays: 14

  DocumentsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentsFunction}
      RetentionInDays: 14

  UploadUrlFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${UploadUrlFunction}
      RetentionInDays: 14

  PingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PingFunction}
      RetentionInDays: 14

  # Error Alarms
  AskFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: doc-qa-ask-errors
      AlarmDescription: Alarm when Ask function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AskFunction
      TreatMissingData: notBreaching

  IngestWorkerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: doc-qa-ingest-worker-errors
      AlarmDescription: Alarm when Ingest Worker has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref IngestWorkerFunction
      TreatMissingData: notBreaching

  # DLQ Alarm (messages in dead letter queue)
  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: doc-qa-dlq-messages
      AlarmDescription: Alarm when messages appear in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt IngestDeadLetterQueue.QueueName
      TreatMissingData: notBreaching

  # Monitoring Dashboard
  DocQaDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: doc-qa-monitoring
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${AskFunction}"],
                  [".", ".", ".", "${IngestFunction}"],
                  [".", ".", ".", "${IngestWorkerFunction}"],
                  [".", ".", ".", "${DocumentsFunction}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "metrics": [
                  ["AWS/Lambda", "Errors", "FunctionName", "${AskFunction}"],
                  [".", ".", ".", "${IngestFunction}"],
                  [".", ".", ".", "${IngestWorkerFunction}"],
                  [".", ".", ".", "${DocumentsFunction}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Duration (Avg)",
                "metrics": [
                  ["AWS/Lambda", "Duration", "FunctionName", "${AskFunction}"],
                  [".", ".", ".", "${IngestWorkerFunction}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "period": 300,
                "stat": "Average"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "SQS Queue Depth",
                "metrics": [
                  ["AWS/SQS", "ApproximateNumberOfMessagesVisible", "QueueName", "doc-qa-ingest-queue"],
                  [".", ".", ".", "doc-qa-ingest-dlq"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "period": 60,
                "stat": "Maximum"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 6,
              "properties": {
                "title": "API Gateway Requests",
                "metrics": [
                  ["AWS/ApiGateway", "Count", "ApiName", "doc-qa-backend"],
                  [".", "4XXError", ".", "."],
                  [".", "5XXError", ".", "."]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "period": 300,
                "stat": "Sum"
              }
            }
          ]
        }

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${DocQaApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  IngestEndpoint:
    Description: Ingest endpoint URL
    Value: !Sub "https://${DocQaApi}.execute-api.${AWS::Region}.amazonaws.com/prod/ingest"
  AskEndpoint:
    Description: Ask endpoint URL
    Value: !Sub "https://${DocQaApi}.execute-api.${AWS::Region}.amazonaws.com/prod/ask"
  DocumentsEndpoint:
    Description: Documents endpoint URL
    Value: !Sub "https://${DocQaApi}.execute-api.${AWS::Region}.amazonaws.com/prod/documents"
  IngestBucket:
    Description: S3 bucket for async ingest
    Value: !Ref DocQaBucket
  UploadUrlEndpoint:
    Description: Upload URL endpoint for presigned S3 URLs
    Value: !Sub "https://${DocQaApi}.execute-api.${AWS::Region}.amazonaws.com/prod/upload-url"
  IngestQueueUrl:
    Description: SQS queue URL for ingest jobs
    Value: !Ref IngestQueue
